[package]
name = "rush-yale-service"
version = "0.1.0"
edition = "2021"
authors = ["Simon Van Der Weide <smvanderweide17@gmail.com>"]
publish = false

[dependencies]
entity = { path = "../entity" }
sea-orm = { version = "0.12.8", features = [ "runtime-tokio-rustls", "sqlx-mysql" ]}
